# Generated by Django 3.2.20 on 2023-12-29 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_auto_20231229_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
