# Generated by Django 3.2.20 on 2023-12-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='suggestion',
        ),
    ]
