# Generated by Django 3.2.20 on 2024-01-14 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_donation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='fromid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fid', to='libraryapp.login_table'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='toid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tid', to='libraryapp.login_table'),
        ),
    ]
