# Generated by Django 3.2.20 on 2024-01-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_auto_20240114_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authbrd',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='authbrd',
            name='time',
        ),
        migrations.RemoveField(
            model_name='authbrd',
            name='writing',
        ),
        migrations.RemoveField(
            model_name='levents',
            name='details',
        ),
        migrations.RemoveField(
            model_name='levents',
            name='event',
        ),
        migrations.RemoveField(
            model_name='levents',
            name='time',
        ),
        migrations.AddField(
            model_name='authbrd',
            name='post',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='levents',
            name='poster',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='shelf_table',
        ),
    ]
